// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 PokeMMO-Prospero contributors
// The overlay's font and logo (loader/src/overlay_assets.c, generated by tools/make_branding.py). Both zlib-compressed.
#pragma once

typedef struct {
    unsigned short x, y, width, height;  // the glyph's cell in the atlas (height is the font's line)
    float advance, bearing;              // pen advance; where the pen sits inside the cell
} OverlayGlyph;
// Codes 1-4 are the controller's face buttons: cross, circle, square, triangle.
enum { OVERLAY_CROSS = 1, OVERLAY_CIRCLE = 2, OVERLAY_SQUARE = 3, OVERLAY_TRIANGLE = 4 };
extern const unsigned overlay_font_width, overlay_font_height, overlay_font_line, overlay_font_ascent;
extern const OverlayGlyph overlay_glyphs[128];
extern const unsigned overlay_font_alpha_size;  // one byte of coverage per atlas pixel
extern const unsigned char overlay_font_alpha[];
extern const unsigned overlay_logo_width, overlay_logo_height;
extern const unsigned overlay_logo_rgba_size;  // RGBA, straight alpha
extern const unsigned char overlay_logo_rgba[];
