#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 PokeMMO-Prospero contributors
"""Renders the file chooser's bitmap font (loader/src/picker_font.c) from DejaVu Sans Mono.

The chooser (adapted from PokeMMO-NX) expects libnx's console font layout: 256 glyphs of 16x16 pixels, each row a
little-endian 16-bit word with bit 15 the leftmost pixel. libnx's own font is not used; this one is generated.
DejaVu fonts: Bitstream Vera / DejaVu license (free to embed and redistribute, see CREDITS.md).

  python3 tools/make_picker_font.py /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype(sys.argv[1], 14)
data = bytearray(256 * 32)
for code in range(256):
    if code < 32 or 127 <= code < 160:
        continue
    image = Image.new("1", (16, 16), 0)
    ImageDraw.Draw(image).text((3, 0), chr(code), font=font, fill=1)
    for y in range(16):
        row = 0
        for x in range(16):
            if image.getpixel((x, y)):
                row |= 1 << (15 - x)
        data[code * 32 + y * 2] = row & 0xFF
        data[code * 32 + y * 2 + 1] = row >> 8
lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
out = Path(__file__).resolve().parents[1] / "loader/src/picker_font.c"
out.write_text("// Generated by tools/make_picker_font.py from DejaVu Sans Mono (DejaVu/Bitstream Vera license). Do not edit.\n"
               "const unsigned char default_font_bin[256 * 32] = {\n    " + ",\n    ".join(lines) + "\n};\n")
print(out)
